### ISSUE TITLE
where is harambe?

### ISSUE THREAD

**Issue by EmilNordling** [SilverbacksStudios/SilverbackLeague#16]
we need a tribute for the one we lost in 2016

![image](https://user-images.githubusercontent.com/8842821/166321710-97563a51-78f5-492c-9c29-a2f203b6de51.png)

**Comment by Martin-Andreasson** [comment]
Status on this issue? @Markusloka

**Comment by LokanderVisiba** [comment]
> Status on this issue? @Markusloka

The status on the implementation of Harambe is ongoing.

**Comment by Markusloka** [comment]
Harmabe is now implemented.
